# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/y/third_year_proj/MP/repo/syn/pipeline_syn.cache/wt [current_project]
set_property parent.project_path D:/y/third_year_proj/MP/repo/syn/pipeline_syn.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/y/third_year_proj/MP/repo/syn/pipeline_syn.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/y/third_year_proj/MP/repo/syn/PC/2to1_mux.v
  D:/y/third_year_proj/MP/repo/syn/PC/4to1_mux.v
  D:/y/third_year_proj/MP/repo/syn/ALU/ALU.v
  D:/y/third_year_proj/MP/repo/syn/CU/BranchUnit_CU.v
  D:/y/third_year_proj/MP/repo/syn/Pipeline/Branch_Unit.v
  D:/y/third_year_proj/MP/repo/syn/ALU/CCR.v
  D:/y/third_year_proj/MP/repo/syn/CU/CU_ALU.v
  D:/y/third_year_proj/MP/repo/syn/CU/CU_CCR.v
  D:/y/third_year_proj/MP/repo/syn/CU/CU_TOP.v
  D:/y/third_year_proj/MP/repo/syn/CU/D_CU.v
  D:/y/third_year_proj/MP/repo/syn/Latches/D_Ex.v
  D:/y/third_year_proj/MP/repo/syn/Latches/Ex_M.v
  D:/y/third_year_proj/MP/repo/syn/Instruction_reg/Instruction_reg.v
  D:/y/third_year_proj/MP/repo/syn/Latches/M_Wb.v
  D:/y/third_year_proj/MP/repo/syn/CU/Mem_CU.v
  D:/y/third_year_proj/MP/repo/syn/Memory/Memory.v
  D:/y/third_year_proj/MP/repo/syn/CU/PC_CU.v
  D:/y/third_year_proj/MP/repo/syn/Register_File/RegFile.v
  D:/y/third_year_proj/MP/repo/syn/Pipeline/Virtual_SP.v
  D:/y/third_year_proj/MP/repo/syn/CU/WB_control.v
  D:/y/third_year_proj/MP/repo/syn/Pipeline/bypass_jmp.v
  D:/y/third_year_proj/MP/repo/syn/CU/hazard_CU.v
  D:/y/third_year_proj/MP/repo/syn/Pipeline/hazard_forwarding_unit.v
  D:/y/third_year_proj/MP/repo/syn/PC/mem_addr_mux.v
  D:/y/third_year_proj/MP/repo/syn/PC/pc_in.v
  D:/y/third_year_proj/MP/repo/syn/PC/pc_reg.v
  D:/y/third_year_proj/MP/repo/syn/Ports/ports_interrupt.v
  D:/y/third_year_proj/MP/repo/syn/TOP/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/y/third_year_proj/MP/repo/syn/constraints.xdc
set_property used_in_implementation false [get_files D:/y/third_year_proj/MP/repo/syn/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcpg236-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
